version: "3.8"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: ecats-test
    image: ecats-test
    build:
      context: ./frontend
      target: production
    ports:
      - "8080:80"
    restart: always

volumes:
  postgres_data:
