version: "3.8"

services:
  backend:
    container_name: ecats-backend
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: ecats-db
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  nginx:
    container_name: ecats-nginx
    build: ./nginx
    volumes:
      - react_build:/var/www/react
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: ecats-frontend
    image: ecats-test
    build:
      context: ./frontend
      # args will load the environment variable from the root .env file, since React won't before build time
      args:
        - REACT_APP_BACKEND_API=${REACT_APP_BACKEND_API}
        - REACT_APP_DEMO_MODE=${REACT_APP_DEMO_MODE}
    volumes:
      - react_build:/app/build

volumes:
  postgres_data:
  react_build:
  static_volume:
