# Generated by Django 3.2.8 on 2021-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
