# Generated by Django 3.2.8 on 2021-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default=''),
        ),
    ]
