# Generated by Django 3.2.8 on 2021-12-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0002_alter_questiontype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='ecats_api.question'),
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datetime_taken', models.DateTimeField()),
                ('test_taker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_instances', to='ecats_api.testtaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('answer_given', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions_answered', to='ecats_api.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions_answered', to='ecats_api.question')),
                ('test_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answered', to='ecats_api.testinstance')),
            ],
            options={
                'verbose_name_plural': 'questions_answered',
            },
        ),
    ]
