# Generated by Django 3.2.8 on 2021-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0003_auto_20211215_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
