# Generated by Django 3.2.8 on 2021-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0004_auto_20211227_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
