# Generated by Django 3.2.8 on 2021-12-27 16:38

from django.db import migrations, models
import ecats_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0005_alter_testtaker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='code',
            field=models.CharField(default=ecats_api.models.random_code, max_length=255),
        ),
    ]
