# Generated by Django 3.2.8 on 2022-01-26 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecats_api', '0007_auto_20220126_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinstance',
            old_name='datetime_taken',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='is_started',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
